version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.5.1
  build:
    commands:
      - echo Build started on `date`
      - echo building
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: dist