FROM node:20.10.0-bookworm-slim as build

WORKDIR /app

ARG VITE_APP_BACKEND_URL

ARG VITE_APP_STORAGE_SERVICE_URL

ARG VITE_APP_TINYMCE_API_KEY

ENV VITE_APP_BACKEND_URL=$VITE_APP_BACKEND_URL

ENV VITE_APP_STORAGE_SERVICE_URL=$VITE_APP_STORAGE_SERVICE_URL

ENV VITE_APP_TINYMCE_API_KEY=$VITE_APP_TINYMCE_API_KEY

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]